import os

API_V1_STR = '/api/v1'

SECRET_KEY = os.getenvb(b'SECRET_KEY')
if not SECRET_KEY:
    SECRET_KEY = os.urandom(32)

ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 * 8  # 60 minutes * 24 hours * 8 days

SERVER_NAME = os.getenv('SERVER_NAME')
SENTRY_DSN = os.getenv('SENTRY_DSN')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')

FIRST_SUPERUSER = os.getenv('FIRST_SUPERUSER')
FIRST_SUPERUSER_PASSWORD = os.getenv('FIRST_SUPERUSER_PASSWORD')